defaults:
  - dataset: default
  - model: default
  - criterion: default
  - optimizer: default
  - scheduler: default
  - trainer: default
  - _self_

train:
  t_domain: [0.0, 1.0]
  x_domain: [0.0, 1.0]

  initial_data:
    shape: [100, 100]
    output_names: ['p', 'sw', 'so', 'uw', 'uo']

  boundary_data:
    shape: [100, 100]
    output_names: ['p', 'sw', 'so', 'uw', 'uo']

  simulation_data:
    shape: [50, 50]
    output_names: ['p', 'sw', 'so', 'uw', 'uo']

  collocation_data:
    shape: [100, 100]

test:
  t_point: 0.1
  x_domain: [0.0, 1.0]
  shape: [1000, 1000]
  output_names: ['p', 'dp_dx', 'sw', 'so', 'uw', 'uo']

logger:
  project_name: flow-simulation-pinn-1D
  entity: null
  run_id: null
  run_name: null
