hydra:
  run:
    dir: ${writer.log_dir}

defaults:
  - _self_
  - model: pinn_mlp
  - dataset: burgers
  - optimizer: adam
  - lr_scheduler: constant
  - criterion: heat_pinn
  - writer: cometml

trainer:
  max_grad_norm: null
  num_steps: 10000
  log_interval: 100
